### ISSUE TITLE
Pillow / Freetype library version skew

### ISSUE THREAD

**Issue by doc-hex** [Coldcard/ckbunker#29]
> When I run ckbunker the captcha image is a broken image on login page ... localhost:9823 ... if i open image in new tab i get ... make_captcha.py line 37 in draw dx,dy  = fn.getsize('W') attribute error 'FreeTypeFont' object has no attribute 'getsize' ... 

I've seen this on another project; the API has changed and "getsize" method isn't offered anymore.

**Comment by scgbckbone** [comment]
https://github.com/Coldcard/ckbunker/pull/30
