### ISSUE TITLE
Tord not working... only Tor browser works

### ISSUE THREAD

**Issue by KISBITCOIN** [Coldcard/ckbunker#6]
Using Mac Catalina V 10.15.7 and python 3.9

Tord is running as a service via brew. When I open ckbunker setup I get 
`Unable to connect to local 'tord' server`in terminal.

When I click 'Operate Tor hidden service' tab in bunker setup page via browser I get
`No local 'tord' server`

Only when I open Tor browser does Ckbunker recognize Tor and allow me to generate an onion address.

**Comment by peter-conalgo** [comment]
I think `tord` from brew vs. the `tord` that's included in the Tor Browser operate on different local port numbers, and that's what you're seeing.

**Comment by KISBITCOIN** [comment]
What can be done to fix the issue ?
