### ISSUE TITLE
TOTP 2FA Show Qr Code on web browser

### ISSUE THREAD

**Issue by KISBITCOIN** [Coldcard/ckbunker#7]
Would be better if the TOTP QR code showed up on web browser for user to setup... couldn't get the phone to pick up the QR code from CC screen, have to manually enter the code in.

**Comment by peter-conalgo** [comment]
Sorry but we can’t do that. Showing the OTP pre-shared secret solely on the Coldcard’s means only your phone and the CC will know it.
