### ISSUE TITLE
Confusing wording in documentation https://ckbunker.com/policy.html#individual-rules

### ISSUE THREAD

**Issue by KISBITCOIN** [Coldcard/ckbunker#8]
![Screen Shot 2021-02-03 at 11 17 36 AM](https://user-images.githubusercontent.com/54788452/106775854-6b0c3d80-663b-11eb-9501-bb8d7d426876.png)
> When an element of the rule is has no value, then the restriction does not apply. For example, if Destination Whitelist is empty, then the Coldcard will not consider the destination address when considering the rule.
> 
> If no rules are defined, then no PSBT will be signed. This can be useful for text message signing applications. On the other hand, an empty rule, allows any transaction to be signed, so be careful!

This reads to me as - if no rules are defined (empty parameter) then no PSBT will be signed, ie... all submitted PSBT's will be denied.

Maybe you should remove the 

> If no rules are defined, then no PSBT will be signed. 

If empty==undefined, you should pick one word and use it throughout documentation. 

My assessment of this section is : if all rules are empty then any PSBT submitted will be signed.

Please clarify so I can explain properly in Guide.

**Comment by peter-conalgo** [comment]
empty != undefined.

- no rules => no PSBT signing
- one empty rule => everything signed (no restrictions)
- more empty rules => same as a single empty rule.

**Comment by KISBITCOIN** [comment]
Thanks. This explanation is much clearer.
