### ISSUE TITLE
Features on Tools page won't work

### ISSUE THREAD

**Issue by KISBITCOIN** [Coldcard/ckbunker#9]
I can't get the recovery tool and address generator to work.. the buttons aren't clickable. I've tried both in setup mode with no policy and with policy outlined below.
<img width="978" alt="Screen Shot 2021-02-05 at 12 12 08 PM" src="https://user-images.githubusercontent.com/54788452/107066183-8f038680-67d5-11eb-8f99-260519d7a20e.png">

![2021-02-05 12 15 10](https://user-images.githubusercontent.com/54788452/107066371-cbcf7d80-67d5-11eb-8ebe-4b16d303d833.jpg)

**Comment by peter-conalgo** [comment]
Sorry we haven't implemented those two buttons yet... (WIP = Work In Progress)
